# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19h6KlQWd5uxMpFy9f77HbtDykLBFnYLG
"""

import zipfile
import os
from PIL import Image

source_zip = "/content/task 7.zip"  # Input zip file
source_folder_unzipped = "/content/task 7 unzipped" # Folder to extract original images
destination_folder_resized = "/content/Task 7 resized images" # Folder to save resized images
destination_zip = "/content/Task 7 resized images.zip" # Output zip file

# Create necessary folders
if not os.path.exists(source_folder_unzipped):
    os.makedirs(source_folder_unzipped)
if not os.path.exists(destination_folder_resized):
    os.makedirs(destination_folder_resized)

# Extract images from the source zip file
with zipfile.ZipFile(source_zip, 'r') as zip_ref:
    zip_ref.extractall(source_folder_unzipped)

new_size = (800, 600)

# Resize images and save to the destination folder
for filename in os.listdir(source_folder_unzipped):
    if filename.lower().endswith((".png", ".jpg", ".jpeg")):
        img_path = os.path.join(source_folder_unzipped, filename)

        try:
            with Image.open(img_path) as img:
                resized_img = img.resize(new_size)
                save_path = os.path.join(destination_folder_resized, filename)
                resized_img.save(save_path)
            print(f"{filename} resized and saved successfully.")
        except Exception as e:
            print(f"Error processing {filename}: {e}")

# Create a new zip file with the resized images
with zipfile.ZipFile(destination_zip, 'w') as zipf:
    for filename in os.listdir(destination_folder_resized):
        file_path = os.path.join(destination_folder_resized, filename)
        zipf.write(file_path, os.path.basename(file_path))

print("All images have been resized and zipped!")